# config/mongo.yml

production:
  uri: <%= ENV['MONGOLAB_URI'] %>

development:
  host: 127.0.0.1
  port: <%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>
  database: benchapp_development

test:
  host: 127.0.0.1
  port: <%= ENV['BOXEN_MONGODB_PORT'] || 27017 %>
  database: benchapp_test
